run:
	gnome-terminal --window -e 'tmux new-session \; \
		send-keys "cd ./backend && uwsgi --http :5000 --gevent 1000 --http-websockets --master --wsgi-file __main__.py --callable app -s 0.0.0.0:3030" C-m \; \
		split-window -v \; \
		send-keys "cd ./frontend && yarn && yarn run serve" C-m \; \
		select-pane -t 1 \; \
		split-window -h \; \
		send-keys "cd ./example && yarn && yarn run serve" C-m \; \
		select-pane -t 4 \;'