run:
	gnome-terminal --window -e 'tmux new-session \; split-window -d \; split-window -h \; select-pane -t 2 \; split-window -h \; select-pane -t 0 \; \
		send-keys "cd ./backend && python3 ." ENTER \; select-pane -t 1 \; \
		send-keys "cd ./openkyc && export PASSWORD="PASSWORD" && FLASK_APP=openkyc.py python3 -m flask run --reload --debugger --host=0.0.0.0 -p 5005" ENTER \; select-pane -t 2 \; \
		send-keys "cd ./frontend && npm run serve-mathias && exec bash" ENTER \; select-pane -t 3 \; \
		send-keys "cd ./example && npm run serve-mathias && exec bash" ENTER \;'