# Default values for threebotlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#tags vary per environment (staging/testing/production) change in according value files.
images:
  login:
    repo: threefolddev/3botlogin
    containerPort: 80
  wizard:
    repo: threefolddev/wizard
    containerPort: 80

services:
  app: 
    name: http
    port: 80
    targetPort: 80
  uwsgi: 
    name: uwgsi
    port: 5000
    targetPort: 5000
  wizard:
    name: wizard
    port: 82
    targetPort: 80

storage:
  type: local
  className: manual
  size: 1Gi
  rights: ReadWriteOnce
  hostpath: "/opt/3botlogin/"

claims:
  data:
    name: threebotlogin
    accessModes: ReadWriteMany
    storage: 2G


acme:
      email: operations@threefold.io


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
