
// Objective-C API for talking to the following Go packages
//
//	github.com/yggdrasil-network/yggdrasil-go/contrib/mobile
//	github.com/yggdrasil-network/yggdrasil-go/src/config
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Yggdrasil_FRAMEWORK_H__
#define __Yggdrasil_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Config.objc.h"
#include "Universe.objc.h"

#endif
