#!/bin/sh

# Ensure git hooks path is set correctly
if ! git config --get core.hooksPath | grep -q "git_hooks"; then
  echo "Setting git hooks path..."
  git config core.hooksPath git_hooks
  echo "Git hooks path set to 'git_hooks'."
else
  echo "Git hooks path already set. Skipping..."
fi

# Get staged Dart files
STAGED_DART_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.dart$')

if [ -n "$STAGED_DART_FILES" ]; then 
  echo "Analyzing staged Dart files..."
  dart analyze --fatal-infos $STAGED_DART_FILES
  ANALYZE_EXIT_CODE=$?

  if [ $ANALYZE_EXIT_CODE -eq 0 ]; then
    exit 0
  fi

  echo "Applying fixes..."
  echo "$STAGED_DART_FILES" | xargs -n1 dart fix --apply

  echo "Re-adding fixed Dart files to the commit..."
  git add .
fi

exit 0