#!/bin/sh

# Function to run Dart command and check exit code
run_command() {
  directory="$1"
  command="$2"

  cd "$directory" || exit 1

  result=$(eval "$command")
  echo "$result"
}

# Ensure git hooks path is set only once
if ! git config --get core.hooksPath | grep -q "git_hooks"; then
  echo "Setting git hooks path..."
  git config core.hooksPath git_hooks
  echo "Git hooks path set to 'git_hooks'."
else
  echo "Git hooks path already set. Skipping..."
fi

# Change directory to app/lib and run dart format
run_command "app/lib" "dart format ." "dart format"

echo "Finished running dart format command."

# Run dart analyze in the current directory
run_command "." "dart analyze ." "dart analyze"

echo "Finished running dart analyze command."

# Run dart fix --apply and add updated files to git
run_command "." "dart fix --apply && git add ." "dart fix"

echo "Finished running dart fix command."