analyzer:
  errors:
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    library_prefixes: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    prefer_interpolation_to_compose_strings: ignore
    prefer_typing_uninitialized_variables: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    avoid_print: true
    prefer_single_quotes: true
