name: threebotlogin
description: A decentralized login application

publish_to: "none"

version: 4.3.1+195

environment:
  sdk: ">=3.4.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_pkid:
    git:
      url: https://github.com/threefoldtech/threefold_connect_flutter_pkid_client
      ref: master
  tfchain_client:
    git:
      url: https://github.com/threefoldtech/tfgrid-sdk-dart
      ref: development
      path: packages/tfchain_client
  stellar_client:
    git:
      url: https://github.com/threefoldtech/tfgrid-sdk-dart
      ref: development
      path: packages/stellar_client
  gridproxy_client:
    git:
      url: https://github.com/threefoldtech/tfgrid-sdk-dart
      ref: development
      path: packages/gridproxy_client
  registrar_client:
    git:
      url: https://github.com/threefoldtech/tfgridv4-sdk-dart
      ref: development
      path: packages/registrar_client
  flutter_svg: ^2.0.17
  bip39: ^1.0.6
  socket_io_client: ^3.1.2
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.5
  http: ^1.3.0
  package_info_plus: ^9.0.0
  google_fonts: ^6.2.1
  flagsmith: ^6.0.0
  flutter_inappwebview: ^6.1.5
  sodium_libs: ^3.4.3+1
  app_links: ^6.3.2
  pbkdf2ns: ^0.0.2
  flutter_json_viewer: ^1.0.1
  device_info_plus: ^12.2.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  open_file: ^3.5.10
  pinenacl: ^0.6.0
  pinput: ^5.0.1
  build_runner: ^2.4.13
  smooth_page_indicator: ^1.2.0+3
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  screen_brightness: ^2.1.1
  validators: ^3.0.0
  lottie: ^3.3.1
  crisp_chat: ^2.2.3
  xml2json: ^6.2.6
  timeago: ^3.7.0
  flutter_widget_from_html: ^0.15.3
  idenfy_sdk_flutter: ^2.6.5
  flutter_riverpod: ^2.6.1
  bs58: ^1.0.0

  convert: ^3.1.2
  crypto: ^3.0.6
  hashlib: ^1.21.1
  stellar_flutter_sdk: ^1.9.2
  flutter_launcher_icons: ^0.14.3
  logger: ^2.5.0
  flutter_keyboard_visibility: ^6.0.0
  mutex: ^3.1.0
  decimal: ^3.2.1
  infinite_scroll_pagination: ^4.1.0
  intl_mobile_field: ^2.1.4
  mobile_scanner: ^7.1.3
  flag: ^7.0.0
  background_fetch: ^1.3.8
  connectivity_plus: ^6.1.4
  awesome_notifications: ^0.10.1
  flutter_secure_storage: ^9.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.19.0
  signer:
    git:
      url: https://github.com/threefoldtech/tfgrid-sdk-dart.git
      path: packages/signer
      ref: development

flutter:
  uses-material-design: true
  assets:
    - assets/circle_images/
    - assets/icons/
    - assets/
