apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "releaseName" . }}
spec:
  dnsNames:
    {{- range $host := .Values.ingress.hosts }}
    - {{ $host.host.domain }}
    {{- end }}
  secretName: {{ template "releaseName" . }}
  issuerRef:
    name: {{ template "releaseName" . }}
    kind: Issuer
