name : Build APK

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Initialize Reflectable
        run: dart run build_runner build    

      - name: Ensure Build Script is Executable
        run: chmod +x build.sh

      - name: Run Build Script
        run: ./build.sh --build --production

      - name: Debug - List APK Files
        run: ls -R build/app/outputs/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/apks/*.apk   