name: Format and Analyze

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: cd app && flutter pub get

      - name: Format Dart files
        run: dart format app/lib

      - name: Analyze Dart code
        run: dart analyze app/lib
